version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.2
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./docker-config/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:7.0-rc
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - postgres
      - redis
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
      - 8080:8080
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --no-assets --node-args="--inspect=0.0.0.0"
  encore:
    image: node:lts-alpine
    working_dir: /app
    entrypoint:
      - yarn
      - encore
      - dev
      - --watch
    volumes:
      - ./:/app:rw

volumes:
  postgres_volume:
  redis_volume: